- name: install epel-release
  action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"

- name: install nginx
  action: "{{ ansible_pkg_mgr }} name=nginx state=present"

- name: stopped firewalld
  service: name=firewalld state=stopped enabled=no









