- name: install nginx
  action: "{{ ansible_pkg_mgr }} name=nginx state=present update_cache=yes"

- name: stopped ufw
  service: name=ufw state=stopped enabled=no

- name: curl nginx.com
  template:
    src: index.j2
    dest: /var/www/html/index.html
    mode: 0644
    backup: yes
  notify:
   - restart webserver
